# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "932ece594967b488067ccf80767cf7c2"
name = "you-may-also-like"
handle = "you-may-also-like-3"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "miniscript-check.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
