# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "46c275e73a1a876a562adda068cfad1d"
name = "add-product-checkout"
handle = "add-product-checkout"
application_url = "https://collections-confused-advocate-senators.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pb-corner.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://collections-confused-advocate-senators.trycloudflare.com/auth/callback",
  "https://collections-confused-advocate-senators.trycloudflare.com/auth/shopify/callback",
  "https://collections-confused-advocate-senators.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
